services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: tallerdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: .
    environment:
      DB_URL: jdbc:postgresql://db:5432/tallerdb
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
      JWT_SECRET: "super-secret-jwt-key-for-production-change-it"
      BOOTSTRAP_ADMIN_USERNAME: admin
      BOOTSTRAP_ADMIN_PASSWORD: Admin1234!
      BOOTSTRAP_ADMIN_FULLNAME: Administrador Taller
    depends_on:
      - db
    ports:
      - "8080:8080"

  frontend:
    build: ./frontend
    depends_on:
      - backend
    ports:
      - "4200:80"

volumes:
  postgres_data:
